name: Compile C Projects

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Only use Ubuntu Linux
    steps:
      - uses: actions/checkout@v3
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest  # Consider specifying a specific Clang version
          platform: x64
      - name: Rename files 
        run: |
          chmod +x rename.sh
          ./rename.sh
      - name: Compile C files
        run: |
          chmod +x compile.sh
          ./compile.sh || exit 1   # Shortened for clarity 
        shell: bash  # Ensure bash is used
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: compiled-linux  # More specific name
          path: |
            **/*
          if-no-files-found: error 
