name: Compile C Projects

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        platform: x64
    - name: Rename files 
      run: |
        chmod +x rename.sh
        ./rename.sh
    - name: Compile C files
      run: |
        chmod +x compile.sh
        # This line executes the 'compile.sh' script and exits with code 1 if the compilation fails.
        ./compile.sh || exit 1
        if [ $? -ne 0 ]; then
          exit 1
        fi
      shell: bash
    - name: Upload Artifacts for Windows
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v3
      with:
        name: compiled-windows
        path: |
          **/*.exe
        if-no-files-found: error
    - name: Upload Artifacts for Unix/Linux
      if: matrix.os != 'windows-latest'
      uses: actions/upload-artifact@v3
      with:
        name: compiled-unix-linux
        path: |
          **/*
        if-no-files-found: error